spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:5002/graphql?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.boot.graphqljava.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8082

logging:
  level:
    graphql: debug

