spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:5002/graphql?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.boot.mybatis.entity
